argo-rollouts:
  controller:
    # -- Labels to be added to the application controller pods
    podLabels:
      env: prod

    # -- The number of controller pods to run
    replicas: 2

    # -- Additional environment variables for rollouts-controller. A list of name/value maps.
    extraEnv:
      - name: STAGE
        value: prod

    # -- Resource limits and requests for the controller pods.
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi