apiVersion: v1
data: null
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/instance: argo-rollouts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
    app.kubernetes.io/version: v1.6.6
    helm.sh/chart: argo-rollouts-2.35.2
  name: argo-rollouts-notification-configmap
  namespace: default
