permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  render-test-manifests-stage:
    name: Render test manifests
    runs-on: ubuntu-latest
    steps:
      - name: Render manifests
        uses: akuity/kargo-render-action@1efacd1d0b6c86ca1d3bc4c842e2b82e36d8f7d7
        with:
          personalAccessToken: ${{ secrets.MY_PAT }}
          targetBranch: env/test
  render-stage-manifests-stage:
    name: Render staging manifests
    runs-on: ubuntu-latest
    steps:
      - name: Render manifests
        uses: akuity/kargo-render-action@1efacd1d0b6c86ca1d3bc4c842e2b82e36d8f7d7
        with:
          personalAccessToken: ${{ secrets.MY_PAT }}
          targetBranch: env/staging
  render-prod-manifests-stage:
    name: Render prod manifests
    runs-on: ubuntu-latest
    steps:
      - name: Render manifests
        uses: akuity/kargo-render-action@1efacd1d0b6c86ca1d3bc4c842e2b82e36d8f7d7
        with:
          personalAccessToken: ${{ secrets.MY_PAT }}
          targetBranch: env/prod
