permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render-manifests:
    name: Render and Commit Manifests (or submit a PR)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetBranch:
          - env/test
          - env/staging
          - env/prod
    steps:
      - uses: blakepettersson/kargo-render-action@blake-test
        with:
          personalAccessToken: ${{ secrets.MY_PAT }}
          targetBranch: ${{ matrix.targetBranch }}
